#!/bin/bash

# Create jobs to pairwise align overlapping projects.
#
# Call:
#       ./create-align-overlapping-projects-pair-jobs <file-list> <chunk-size>

n=`wc -l < ${1}`
mod=${2:-100}

step=$(($mod/2))
first=0
last=$(($n-1))

mkdir -p jobs
mkdir -p export

range="$first-$(($first+2*$step-1))"
range1="$first-$(($first+$step-1))"
range2="$first-$(($first+2*$step-1))"

job="jobs/align-overlapping-projects-pair-$range"

fijicmd="${HOME}/packages/Fiji.app/ImageJ-linux64 -Xms10g -Xmx10g"

echo "#!/bin/bash" > $job
pwd=$PWD
echo "xvfb-run -a $fijicmd -Ddir1=$pwd/$range1 -Ddir2=$pwd/$range2 -- --no-splash ${pwd}/align-overlapping-projects-pair.bsh" >> $job
chmod a+x $job


#for i in `seq $first $step $(($last-3*$step))` 
for i in `seq $first $step $(($last-$step))` 
do
	range="$i-$(($i+3*$step-1))"
	range1="$i-$(($i+2*$step-1))"
	range2="$(($i+$step))-$(($i+3*$step-1))"
	pwd=`pwd`
	job="jobs/align-overlapping-projects-pair-$range"

	echo "#!/bin/bash" > $job
	echo "xvfb-run -a $fijicmd -Ddir1=$pwd/$range1 -Ddir2=$pwd/$range2 -- --no-splash ${pwd}/align-overlapping-projects-pair.bsh" >> $job
	chmod a+x $job
done

